RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd /root/.ssh /projects


# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    sed -i "s/.*AuthorizedKeysFile.*/AuthorizedKeysFile\t\~\/.ssh\/authorized_keys/g" /etc/ssh/sshd_config

#SSH CUDA fix

RUN echo "export PATH=$PATH" >> /etc/profile && \
    echo "ldconfig" >> /etc/profile

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

WORKDIR /projects

COPY scripts/run_server.sh /

CMD /run_server.sh
